name: Checkov

on:
  push:
  pull_request:

jobs:
  scan-ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install checkov==3.3.10
      - run: checkov -d . --framework ansible
